# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8  #请求url 字符编码
        max-threads: 1000 #内置tomcat最大连接数
        min-spare-threads: 30
    port: 8080   # 端口
    servlet:
      context-path: /admin  #上下文访问路径
# spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/esaybug?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect   # 决定生成的sql，和连接的数据库对应
        hbm2ddl:
          auto: update # 常用属性；作用：第一次启动访问后，会根据entity 注解配置创建表，后面再次启动时只对比数据库更新，不创建，也不删除原有数据
    show-sql: true  # 是否打印SQL




